// Patterns are matched against a diacritic-stripped, lowercased name, so
// Romanian words with diacritics (lapte, brânză, pâine...) and their
// plain-letter spellings (branza, paine...) both match.
const ICON_RULES: Array<[RegExp, string]> = [
  [/\b(milk|almond milk|oat milk|soy milk|lapte)\b/, "🥛"],
  [/\b(egg|eggs|ou|oua|oue)\b/, "🥚"],
  [/\b(bread|baguette|loaf|bun|bagel|toast|paine|franzela|covrig)\b/, "🍞"],
  [/\b(croissant|pretzel|pita)\b/, "🥐"],
  [/\b(muffin)\b/, "🧁"],
  [/\b(butter|margarine|unt)\b/, "🧈"],
  [/\b(cheese|mozzarella|cheddar|feta|parmesan|branza|cascaval|telemea|ricotta)\b/, "🧀"],
  [/\b(cottage cheese|branza de vaci|urda)\b/, "🧀"],
  [/\b(cream|sour cream|whipped cream|smantana|frisca)\b/, "🥛"],
  [/\b(yogurt|yoghurt|iaurt)\b/, "🥣"],
  [/\b(apple|apples|mar|mere)\b/, "🍎"],
  [/\b(banana|bananas|banane)\b/, "🍌"],
  [/\b(orange|oranges|mandarin|tangerine|portocale|portocala)\b/, "🍊"],
  [/\b(lemon|lime|lamaie|lamai)\b/, "🍋"],
  [/\b(grape|grapes|struguri)\b/, "🍇"],
  [/\b(strawberr(y|ies)|capsuni|capsuna)\b/, "🍓"],
  [/\b(blueberr(y|ies)|afine)\b/, "🫐"],
  [/\b(raspberr(y|ies)|blackberr(y|ies)|zmeura|mure)\b/, "🍇"],
  [/\b(watermelon|pepene verde|pepene)\b/, "🍉"],
  [/\b(melon|cantaloupe|pepene galben)\b/, "🍈"],
  [/\b(pineapple|ananas)\b/, "🍍"],
  [/\b(peach|peaches|piersica|piersici)\b/, "🍑"],
  [/\b(cherry|cherries|cirese|cireasa)\b/, "🍒"],
  [/\b(plum|plums|prune|prunes)\b/, "🍑"],
  [/\b(apricot|apricots|caise|caisa)\b/, "🍑"],
  [/\b(kiwi)\b/, "🥝"],
  [/\b(mango)\b/, "🥭"],
  [/\b(coconut|nuca de cocos)\b/, "🥥"],
  [/\b(fig|figs|smochine)\b/, "🍈"],
  [/\b(pomegranate|rodie)\b/, "🍎"],
  [/\b(avocado)\b/, "🥑"],
  [/\b(tomato|tomatoes|rosie|rosii)\b/, "🍅"],
  [/\b(potato|potatoes|cartof|cartofi)\b/, "🥔"],
  [/\b(sweet potato|cartof dulce)\b/, "🍠"],
  [/\b(carrot|carrots|morcov|morcovi)\b/, "🥕"],
  [/\b(onion|onions|shallot|ceapa)\b/, "🧅"],
  [/\b(leek|praz)\b/, "🧅"],
  [/\b(garlic|usturoi)\b/, "🧄"],
  [/\b(pepper|peppers|bell pepper|chili|chilli|ardei)\b/, "🌶️"],
  [/\b(corn|porumb)\b/, "🌽"],
  [/\b(cucumber|castravete|castraveti)\b/, "🥒"],
  [/\b(broccoli)\b/, "🥦"],
  [/\b(cauliflower|conopida)\b/, "🥦"],
  [/\b(cabbage|varza)\b/, "🥬"],
  [/\b(lettuce|salad|greens|spinach|kale|salata|spanac)\b/, "🥬"],
  [/\b(eggplant|aubergine|vinete|vinata)\b/, "🍆"],
  [/\b(zucchini|courgette|dovlecel|dovlecei)\b/, "🥒"],
  [/\b(pumpkin|squash|dovleac)\b/, "🎃"],
  [/\b(beet|beetroot|sfecla)\b/, "🥕"],
  [/\b(celery|telina)\b/, "🥬"],
  [/\b(radish|ridichi)\b/, "🥕"],
  [/\b(asparagus|sparanghel)\b/, "🥬"],
  [/\b(peas|mazare)\b/, "🫛"],
  [/\b(green beans|fasole verde)\b/, "🫛"],
  [/\b(beans|fasole)\b/, "🫘"],
  [/\b(lentils|linte)\b/, "🫘"],
  [/\b(chickpeas|naut)\b/, "🫘"],
  [/\b(mushroom|mushrooms|ciuperca|ciuperci)\b/, "🍄"],
  [/\b(herbs|basil|busuioc|parsley|patrunjel|dill|marar|mint|menta|oregano|thyme|cimbru|rosemary|rozmarin)\b/, "🌿"],
  [/\b(chicken|poultry|turkey|pui|curcan)\b/, "🍗"],
  [/\b(duck|rata)\b/, "🦆"],
  [/\b(beef|steak|meat|carne|vita)\b/, "🥩"],
  [/\b(pork|porc)\b/, "🥩"],
  [/\b(lamb|miel)\b/, "🥩"],
  [/\b(liver|ficat)\b/, "🥩"],
  [/\b(meatball|meatballs|chiftea|chiftele)\b/, "🍖"],
  [/\b(bacon|ham|sausage|salami|prosciutto|sunca|carnati|carnat)\b/, "🥓"],
  [/\b(fish|salmon|tuna|cod|peste|somon)\b/, "🐟"],
  [/\b(shrimp|prawn|prawns|creveti|creveta)\b/, "🦐"],
  [/\b(crab|lobster|crab|homar)\b/, "🦀"],
  [/\b(squid|octopus|calamar|caracatita)\b/, "🦑"],
  [/\b(mussels|oysters|midii|stridii)\b/, "🦪"],
  [/\b(tofu|tempeh)\b/, "🧈"],
  [/\b(rice|orez)\b/, "🍚"],
  [/\b(quinoa|couscous)\b/, "🍚"],
  [/\b(pasta|spaghetti|noodles|macaroni|paste)\b/, "🍝"],
  [/\b(pizza)\b/, "🍕"],
  [/\b(cereal|oats|oatmeal|granola|muesli|cereale|ovaz)\b/, "🥣"],
  [/\b(flour|faina)\b/, "🌾"],
  [/\b(breadcrumbs|pesmet)\b/, "🌾"],
  [/\b(yeast|drojdie)\b/, "🌾"],
  [/\b(baking powder|praf de copt)\b/, "🌾"],
  [/\b(sugar|zahar)\b/, "🧂"],
  [/\b(salt|sare)\b/, "🧂"],
  [/\b(spice|spices|condimente|condiment)\b/, "🧂"],
  [/\b(cinnamon|scortisoara)\b/, "🧂"],
  [/\b(vanilla|vanilie)\b/, "🧂"],
  [/\b(honey|miere)\b/, "🍯"],
  [/\b(jam|marmalade|preserve|gem|dulceata)\b/, "🍓"],
  [/\b(chocolate|cocoa|nutella|ciocolata)\b/, "🍫"],
  [/\b(candy|sweets|gummy|bomboane|dulciuri)\b/, "🍬"],
  [/\b(cookie|cookies|biscuit|biscuiti|biscuite)\b/, "🍪"],
  [/\b(crackers|biscuiti sarati)\b/, "🍘"],
  [/\b(cake|tort|prajitura)\b/, "🍰"],
  [/\b(ice cream|gelato|inghetata)\b/, "🍦"],
  [/\b(popcorn|floricele)\b/, "🍿"],
  [/\b(chips|crisps|chipsuri)\b/, "🥔"],
  [/\b(nuts|almond|almonds|walnut|peanut|cashew|nuci|alune|migdale)\b/, "🥜"],
  [/\b(coffee|espresso|cafea)\b/, "☕"],
  [/\b(tea|ceai)\b/, "🍵"],
  [/\b(juice|suc)\b/, "🧃"],
  [/\b(smoothie|milkshake)\b/, "🥤"],
  [/\b(lemonade|limonada)\b/, "🍋"],
  [/\b(water|sparkling water|apa)\b/, "💧"],
  [/\b(soda|cola|soft drink|suc acidulat)\b/, "🥤"],
  [/\b(energy drink)\b/, "🥤"],
  [/\b(beer|bere)\b/, "🍺"],
  [/\b(wine|vin)\b/, "🍷"],
  [/\b(champagne|sampanie|prosecco)\b/, "🍾"],
  [/\b(whiskey|whisky|vodka|rum|gin|cider)\b/, "🥃"],
  [/\b(oil|olive oil|ulei)\b/, "🫒"],
  [/\b(vinegar|otet)\b/, "🍶"],
  [/\b(soy sauce|sos de soia)\b/, "🍶"],
  [/\b(sauce|ketchup|mustard|mayo|mayonnaise|sos|mustar)\b/, "🍯"],
  [/\b(soup|supa|ciorba)\b/, "🍲"],
  [/\b(tortilla|wrap|taco)\b/, "🌮"],
  [/\b(pie|placinta)\b/, "🥧"],
  [/\b(diaper|diapers|nappies|scutec|scutece)\b/, "🍼"],
  [/\b(baby food|formula|lapte praf)\b/, "🍼"],
  [/\b(pacifier|suzeta)\b/, "🍼"],
  [/\b(baby wipes|servetele umede)\b/, "🧻"],
  [/\b(toilet paper|tissue|napkin|paper towel|hartie igienica|servetele)\b/, "🧻"],
  [/\b(soap|detergent|cleaner|cleaning|sapun|balsam de rufe)\b/, "🧼"],
  [/\b(dish soap|detergent de vase)\b/, "🧼"],
  [/\b(sponge|burete)\b/, "🧽"],
  [/\b(broom|matura|mop)\b/, "🧹"],
  [/\b(bucket|galeata)\b/, "🪣"],
  [/\b(gloves|manusi)\b/, "🧤"],
  [/\b(foil|aluminum foil|folie de aluminiu|cling film|folie alimentara)\b/, "🧻"],
  [/\b(matches|chibrituri|lighter|bricheta)\b/, "🔥"],
  [/\b(toothpaste|toothbrush|pasta de dinti|periuta|floss|ata dentara)\b/, "🪥"],
  [/\b(shampoo|sampon)\b/, "🧴"],
  [/\b(conditioner|balsam)\b/, "🧴"],
  [/\b(deodorant)\b/, "🧴"],
  [/\b(lotion|crema|sunscreen|crema de plaja)\b/, "🧴"],
  [/\b(perfume|parfum)\b/, "🧴"],
  [/\b(razor|aparat de ras)\b/, "🪒"],
  [/\b(pads|tampoane)\b/, "🧴"],
  [/\b(trash bag|garbage bag|bin bag|punga de gunoi|saci menajeri)\b/, "🗑️"],
  [/\b(battery|batteries|baterie|baterii)\b/, "🔋"],
  [/\b(light bulb|bulb|bec)\b/, "💡"],
  [/\b(flower|flowers|bouquet|flori)\b/, "💐"],
  [/\b(plant|planta)\b/, "🪴"],
  [/\b(candle|lumanare)\b/, "🕯️"],
  [/\b(medicine|pill|vitamin|vitamins|medicament|pastile|vitamine)\b/, "💊"],
  [/\b(mask|masca)\b/, "😷"],
  [/\b(dog food|cat food|pet food|mancare caine|mancare pisica)\b/, "🐾"],
  [/\b(cat litter|asternut pisica|leash|lesa)\b/, "🐾"],
  [/\b(pen|pix|pencil|creion|notebook|caiet)\b/, "✏️"],
  [/\b(tape|banda adeziva|string|sfoara)\b/, "🧵"],
];

export function normalize(name: string): string {
  return name
    .toLowerCase()
    .replace(/[ăâ]/g, "a")
    .replace(/î/g, "i")
    .replace(/[șş]/g, "s")
    .replace(/[țţ]/g, "t");
}

export function getItemIcon(name: string): string {
  const normalized = normalize(name);
  for (const [pattern, icon] of ICON_RULES) {
    if (pattern.test(normalized)) return icon;
  }
  return "🛒";
}
