const ICON_RULES: Array<[RegExp, string]> = [
  [/\b(milk|almond milk|oat milk|soy milk)\b/, "🥛"],
  [/\b(egg|eggs)\b/, "🥚"],
  [/\b(bread|baguette|loaf|bun|bagel|toast)\b/, "🍞"],
  [/\b(butter|margarine)\b/, "🧈"],
  [/\b(cheese|mozzarella|cheddar|feta|parmesan)\b/, "🧀"],
  [/\b(yogurt|yoghurt)\b/, "🥣"],
  [/\b(apple|apples)\b/, "🍎"],
  [/\b(banana|bananas)\b/, "🍌"],
  [/\b(orange|oranges|mandarin|tangerine)\b/, "🍊"],
  [/\b(lemon|lime)\b/, "🍋"],
  [/\b(grape|grapes)\b/, "🍇"],
  [/\b(strawberr(y|ies))\b/, "🍓"],
  [/\b(watermelon)\b/, "🍉"],
  [/\b(pineapple)\b/, "🍍"],
  [/\b(peach|peaches)\b/, "🍑"],
  [/\b(cherry|cherries)\b/, "🍒"],
  [/\b(avocado)\b/, "🥑"],
  [/\b(tomato|tomatoes)\b/, "🍅"],
  [/\b(potato|potatoes)\b/, "🥔"],
  [/\b(carrot|carrots)\b/, "🥕"],
  [/\b(onion|onions|shallot)\b/, "🧅"],
  [/\b(garlic)\b/, "🧄"],
  [/\b(pepper|peppers|bell pepper|chili|chilli)\b/, "🌶️"],
  [/\b(corn)\b/, "🌽"],
  [/\b(cucumber)\b/, "🥒"],
  [/\b(broccoli)\b/, "🥦"],
  [/\b(lettuce|salad|greens|spinach|kale)\b/, "🥬"],
  [/\b(mushroom|mushrooms)\b/, "🍄"],
  [/\b(chicken|poultry|turkey)\b/, "🍗"],
  [/\b(beef|steak|meat)\b/, "🥩"],
  [/\b(bacon|ham|sausage|salami|prosciutto)\b/, "🥓"],
  [/\b(fish|salmon|tuna|cod)\b/, "🐟"],
  [/\b(shrimp|prawn|prawns)\b/, "🦐"],
  [/\b(rice)\b/, "🍚"],
  [/\b(pasta|spaghetti|noodles|macaroni)\b/, "🍝"],
  [/\b(pizza)\b/, "🍕"],
  [/\b(cereal|oats|oatmeal|granola|muesli)\b/, "🥣"],
  [/\b(flour)\b/, "🌾"],
  [/\b(sugar)\b/, "🧂"],
  [/\b(salt)\b/, "🧂"],
  [/\b(honey)\b/, "🍯"],
  [/\b(jam|marmalade|preserve)\b/, "🍓"],
  [/\b(chocolate|cocoa|nutella)\b/, "🍫"],
  [/\b(candy|sweets|gummy)\b/, "🍬"],
  [/\b(cookie|cookies|biscuit)\b/, "🍪"],
  [/\b(cake)\b/, "🍰"],
  [/\b(ice cream|gelato)\b/, "🍦"],
  [/\b(popcorn)\b/, "🍿"],
  [/\b(chips|crisps)\b/, "🥔"],
  [/\b(nuts|almond|almonds|walnut|peanut|cashew)\b/, "🥜"],
  [/\b(coffee|espresso)\b/, "☕"],
  [/\b(tea)\b/, "🍵"],
  [/\b(juice)\b/, "🧃"],
  [/\b(water|sparkling water)\b/, "💧"],
  [/\b(soda|cola|soft drink)\b/, "🥤"],
  [/\b(beer)\b/, "🍺"],
  [/\b(wine)\b/, "🍷"],
  [/\b(oil|olive oil)\b/, "🫒"],
  [/\b(vinegar)\b/, "🍶"],
  [/\b(sauce|ketchup|mustard|mayo|mayonnaise)\b/, "🍯"],
  [/\b(soup)\b/, "🍲"],
  [/\b(tortilla|wrap|taco)\b/, "🌮"],
  [/\b(pie)\b/, "🥧"],
  [/\b(diaper|diapers|nappies)\b/, "🍼"],
  [/\b(baby food|formula)\b/, "🍼"],
  [/\b(toilet paper|tissue|napkin|paper towel)\b/, "🧻"],
  [/\b(soap|detergent|cleaner|cleaning)\b/, "🧼"],
  [/\b(sponge)\b/, "🧽"],
  [/\b(toothpaste|toothbrush)\b/, "🪥"],
  [/\b(shampoo|conditioner)\b/, "🧴"],
  [/\b(trash bag|garbage bag|bin bag)\b/, "🗑️"],
  [/\b(battery|batteries)\b/, "🔋"],
  [/\b(light bulb|bulb)\b/, "💡"],
  [/\b(flower|flowers|bouquet)\b/, "💐"],
  [/\b(plant)\b/, "🪴"],
  [/\b(candle)\b/, "🕯️"],
  [/\b(medicine|pill|vitamin|vitamins)\b/, "💊"],
  [/\b(mask)\b/, "😷"],
  [/\b(dog food|cat food|pet food)\b/, "🐾"],
];

export function getItemIcon(name: string): string {
  const normalized = name.toLowerCase();
  for (const [pattern, icon] of ICON_RULES) {
    if (pattern.test(normalized)) return icon;
  }
  return "🛒";
}
